### PR TITLE
PSR/Cache 2.0 compatibility

### PR DESCRIPTION
**Pull request by realsim**

### CODE REVIEW

**Review by migo315 — APPROVED** [review]
Looks goods ;-)

**Review by migo315 — APPROVED** [review]

**Comment by migo315** [comment]
I cannot merge or change settings anymore. Maybe you can check / merge it, @avareldev?

**Comment by Matts** [comment]
Lol so basically I just made a MR to do exactly this and then noticed that it has already been done. Any chance a version can be released soon?

/duplicated by #25 

@avareldev poke :)

**Review by sauls — APPROVED** [review]

**Comment by mKnoop** [comment]
Thanks for the contribution but we have already merged the same change in another pr.

The support will be released in the next version.

**Pull request closed without merging**
