### PR TITLE
add php 8.1 support

### PR DESCRIPTION
**Pull request by goetas**

### CODE REVIEW

**Comment by goetas** [comment]
@migo315  it would be great to have a review from you here

**Comment by migo315** [comment]
> @migo315 it would be great to have a review from you here

Unfortunately, due to my job change, I am no longer a maintainer of this repository and therefore no longer have any permissions.

@mKnoop @avareldev Can you review the open pr's?

**Comment by goetas** [comment]
@migo315 are you interested in giving me write permissions ?   here is my profile https://github.com/goetas and i'm using at work this project

**Comment by migo315** [comment]
> @migo315 are you interested in giving me write permissions ? here is my profile https://github.com/goetas and i'm using at work this project

As I said, I no longer have permissions in this repository. I can't merge or change any settings. You'll have to contact the owner bestit.

**Comment by goetas** [comment]
@migo315  aaa, now i understand. Thanks for the info

**Review by sigbits-mvl — APPROVED** [review]

**Comment by mKnoop** [comment]
Thanks a lot for the contribution but we have decided not to drop the support for php 5.6. 

We have adapted you changes for php 8.1 in another pr and this will be released in the next version.

**Pull request closed without merging**
