### PR TITLE
PHP 8 compatibility

### PR DESCRIPTION
**Pull request by Schleuse**
This PR makes flagception installable under PHP 8. The most difficult part was to make the existing Tests [compatible](https://phpunit.de/supported-versions.html) with both:

- PHPUnit 5.5 which is required for PHP 5.6 compability
- PHPUnit 8+ which is required for PHP 8.0 compability

To make this happen, I've had to move the logic of one Test `setUp`-Method into the test-code (207772c6769772dfb21bea5cd46ad23d5dce766d).

### CODE REVIEW

**Comment by Schleuse** [comment]
There remain some incompatibilities with:

Phing (should be resolved in `3.x`: https://github.com/phingofficial/phing/blob/master/CHANGELOG.md#jan-x-2021---phing-300-rc1):

```
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /home/travis/build/bestit/flagception-sdk/vendor/phing/phing/classes/phing/tasks/system/CvsPassTask.php on line 390
```

PHP_CodeSniffer:
```
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/travis/build/bestit/flagception-sdk/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2028
```

Maybe it's time to update the tooling :man_shrugging:

**Comment by migo315** [comment]
Thanks for your help @Schleuse ;-) 

You can safely remove Phing and just call the QA tools directly (or wait some days and I remove Phing the next days). I don't see the need to use Phing anymore.

**Comment by Schleuse** [comment]
@migo315 I've removed `phing` and replaced it with composer scripts. I've also updated `php-coveralls` and `php-codesniffer` to the latest version.

**Comment by migo315** [comment]
Really great work! Thank you! 👍

**Review by migo315 — APPROVED** [review]

**Pull request merged**
